name: Build and Test .NET 5 CI

on:
  push:
    paths-ignore:
    - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103
    - name: Build with dotnet
      run: |
        dotnet build ArdalisSpecification/src/Ardalis.Specification/Ardalis.Specification.csproj --configuration Release
        dotnet build ArdalisSpecification/tests/Ardalis.Specification.UnitTests/Ardalis.Specification.UnitTests.csproj --configuration Release
        dotnet build ArdalisSpecificationEF/src/Ardalis.Specification.EF/Ardalis.Specification.EntityFrameworkCore.csproj --configuration Release
        dotnet build ArdalisSpecificationEF/tests/Ardalis.Specification.EF.IntegrationTests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests.csproj --configuration Release
    - name: chmod
      run: chmod 555 ./RunTests.sh
    - name: Run integration tests with Docker
      run: ./RunTests.sh
