name: Build and Test .NET 5 CI

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'Specification/**'
      - 'Specification.EntityFrameworkCore/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Specification/**'
      - 'Specification.EntityFrameworkCore/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build with dotnet
      run: |
        dotnet build Specification/src/Ardalis.Specification/Ardalis.Specification.csproj --configuration Release
        dotnet build Specification/tests/Ardalis.Specification.UnitTests/Ardalis.Specification.UnitTests.csproj --configuration Release
        dotnet build Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Ardalis.Specification.EntityFrameworkCore.csproj --configuration Release
        dotnet build Specification.EntityFrameworkCore/tests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests.csproj --configuration Release
    - name: chmod
      run: chmod 555 ./RunTests.sh
    - name: Run integration tests with Docker
      run: ./RunTests.sh
